### PR TITLE
[12.0][MIG] change_management

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
lack_green

**Comment by MiquelRForgeFlow** [comment]
green

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Not working:

- Go to a project and then click on Changes button. 
`Uncaught Error: NameError: name 'uid' is not defined`

- Create a change from the change menu. Try to confirm it. I get:
`TypeError: 2019-10-22 10:11:22 (field change.management.change.date_confirmed) must be string or date, not datetime.`

Almost there keep going :)

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
`AttributeError: type object 'Date' has no attribute 'now'`

when confirming a change order

also the button form the project also fails, the same error commented.

:-1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional LGTM

**Comment by MiquelRForgeFlow** [comment]
i-am-ready

**Pull request merged**
