### PR TITLE
[FIX] Correct gross_profit_plan calculation

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
Don't think I need to explain? :)

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Opps I think I make a mistake merging, the total plan cost is actually a negative amount (negative means cost). Have you checked? Probably this need to be reverted.

**Comment by CasVissers-360ERP** [comment]
I have:
 account.total_cost_plan = ( account.material_cost_plan + account.labor_cost_plan)
 account.material_cost_plan = (-1*

So I think the fix is correct?

**Comment by AaronHForgeFlow** [comment]
I think you are right. they are stored as positive. Thanks for the notice

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow This commit has been reverted or did you fix in a different way?

**Comment by AaronHForgeFlow** [comment]
@CasVissers  I reverted the commit here https://github.com/ForgeFlow/eficent-odoo-addons/commit/b6baf5695f8a49185ee16b408fe9a62775d7a82c because it was causing CI checks to fail. I remember to test and the cost value was already negative. Do you find a case where costs are actually positive in your use case? Perhaps a third module was affecting this bu I don't think that. Sorry  I did not ping you when I reverted that.

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
I know understand what is going wrong. The customer, or the customer I trained, registers planned costs with a negative sign. When doing this the amount in Planned Costs & Revenues represents the margin. Think I will have to re-train my customer.

**Comment by AaronHForgeFlow** [comment]
That sound familiar to me. People tends to write costs as positive. BTW perhaps this module could be useful for them:  https://github.com/ForgeFlow/project-bid/tree/12.0/analytic_plan_mass_create it helps to create planned costs from the analytic account.

**Comment by CasVissers-360ERP** [comment]
Now I'm confused again:

If we take costs planned material is -500 for example

`                account.material_cost_plan = (
                    -1
                    * self._get_plan_journal_item_totals(
                        material_journal_ids.ids,
                        analytic_account_ids,
                        account.active_analytic_planning_version.id,
                    )`

Here we do -1 * -500 so we have 500

`    @api.multi
    def compute_total_cost_plan(self):
        for account in self:
            account.total_cost_plan = (
                account.material_cost_plan + account.labor_cost_plan
            )`
Still 500

`    @api.multi
    @api.depends("total_cost_plan", "revenue_plan")
    def compute_gross_profit_plan(self):
        for account in self:
            account.gross_profit_plan = (
                account.revenue_plan + account.total_cost_plan
            )`

If revenue plan is 1000, gross profit would be 1500?

Will definitely test the mass create module!

**Comment by AaronHForgeFlow** [comment]
hmm yes, I am confused too. could it be `_get_plan_journal_item_totals` returns a positive number? It does perform a read_group. I don't thing read group changes the sign, but need to test. It is quite strange because the code it is the same in v10 and have not get any complains from my customer.

**Comment by CasVissers-360ERP** [comment]
I don't see why _get_plan_journal_item_totals should return a positive number. Just to be sure, in plan items:
costs are written as negative i.e. -500
turnover is written as positive i.e. 1000

Is there a runbot or env where we can validate?

**Comment by AaronHForgeFlow** [comment]
> costs are written as negative i.e. -500
turnover is written as positive i.e. 1000

Yes, that is correct.

> I don't see why _get_plan_journal_item_totals should return a positive number

Me neither. Unfortunately there is no runbot to test.

It seems to me that your fix was correct, the error must be in the tests. I need to review them again. Last time I reviewed the tests they seemed correct to me but it is clear there must me some error somewhere. Will create another PR with your commit again as starting point.

**Pull request merged**
