### PR TITLE
[10.0] [IMP] Added Unit Test cases

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Added a unit test case for analytic_resource_plan_stock_picking.

@aheficent

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
First test passed. Pending for the second one.

**Comment by nikul-serpentcs** [comment]
@aheficent Second test Done, Could you please review.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
