### PR TITLE
[10.0] [ADD] analytic_resource_plan_stock_picking

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Analytic Resource Planning - get resources
==========================================
Module features:
    - prepare the stock for the project
    - create Purchase request if there are not enough qty in stock

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
Besides, can you please make it depend on analytic_resource_plan?

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
@nikul-serpentcs I will do it as soon as the dependencies are migrated. Regards

**Review by AaronHForgeFlow — COMMENTED** [review]
Will fix

**Pull request merged**
