### PR TITLE
[14.0][MIG] stock_analytic_account

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**

### CODE REVIEW

**Review by JuanyDForgeflow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
I am not completely sure it is due this module or some dependency module. I created a blank database and installed this module. Then when trying to access an analytic account I am getting this error:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 908, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1372, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1364, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1527, in load_views
    result['fields_views'] = {
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1528, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
  File "/opt/odoo/auto/addons/web/models/models.py", line 246, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1625, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-46>", line 2, in get_bindings
  File "/opt/odoo/custom/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_actions.py", line 117, in get_bindings
    result[binding_type].append(action.read()[0])
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_actions.py", line 250, in read
    values['help'] = self.with_context(**ctx).env[model].get_empty_list_help(values.get('help', ''))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: with_context() argument after ** must be a mapping, not str
```

Does it sound familiar?

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
I uninstalled this module but keep all the other dependencies installed. The error disapeared. I think there is view in this module that is causing the error. Can you check?

**Comment by JasminSForgeFlow** [comment]
> I uninstalled this module but keep all the other dependencies installed. The error disapeared. I think there is view in this module that is causing the error. Can you check?

Sure, will check and fix it.

**Comment by JasminSForgeFlow** [comment]
@AaronHForgeFlow its fixed.
Thanks

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
All good. Thanks

**Pull request merged**
